apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:9.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: "GF_AUTH_ANONYMOUS_ENABLED"
          value: "false"
        - name: "GF_AUTH_ANONYMOUS_ORG_ROLE"
          value: "Admin"
        - name: "GF_AUTH_BASIC_ENABLED"
          value: "false"
        - name: "GF_SECURITY_ADMIN_PASSWORD"
          value: "demo"
        - name: "GF_SECURITY_ADMIN_USER"
          value: "devops"
        - name: "GF_SMTP_ENABLED"
          value: "true"
        - name: "GF_SMTP_HOST"
          value: "smtp.gmail.com:587"
        - name: "GF_SMTP_FROM_ADDRESS"
          value: "mcnayana47@gmail.com"
        - name: "GF_SMTP_USER"
          value: "mcnayana47@gmail.com"
        - name: "GF_SMTP_PASSWORD"
          value: "hmxa ajak owcz nvab"
        - name: "GF_SMTP_SKIP_VERIFY"
          value: "false"
        volumeMounts:
          - mountPath: /var/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          hostPath:
            path: /devops/grafana-data
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
